# Generated by Django 5.1.4 on 2026-09-16 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('joining_date', models.DateField()),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(choices=[('civil', 'Civil'), ('electrical', 'Electrical'), ('plumbing', 'Plumbing'), ('management', 'Management'), ('labour', 'Labour'), ('other', 'Other')], default='labour', max_length=30)),
                ('employee_type', models.CharField(choices=[('engineer', 'Engineer'), ('architect', 'Architect'), ('supervisor', 'Supervisor'), ('mason', 'Mason'), ('carpenter', 'Carpenter'), ('electrician', 'Electrician'), ('plumber', 'Plumber'), ('labour', 'Labour / Worker'), ('driver', 'Driver'), ('other', 'Other')], default='labour', max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='projects.project')),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['full_name'],
            },
        ),
    ]
