# Generated by Django 5.1.4 on 2026-09-16 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('earthmoving', 'Earth Moving'), ('lifting', 'Lifting'), ('concrete', 'Concrete'), ('transport', 'Transport'), ('compaction', 'Compaction'), ('other', 'Other')], default='other', max_length=20)),
                ('owner_vendor', models.CharField(blank=True, max_length=200)),
                ('rental_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rental_per', models.CharField(blank=True, default='day', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Under Maintenance'), ('retired', 'Retired')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='projects.project')),
            ],
            options={
                'db_table': 'equipment',
                'ordering': ['name'],
            },
        ),
    ]
