# Generated by Django 5.1.4 on 2026-09-16 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('cement', 'Cement'), ('steel', 'Steel'), ('sand', 'Sand'), ('bricks', 'Bricks'), ('paint', 'Paint'), ('tiles', 'Tiles'), ('aggregate', 'Aggregate'), ('electrical', 'Electrical Material'), ('plumbing', 'Plumbing Material'), ('wood', 'Wood / Timber'), ('glass', 'Glass'), ('other', 'Other')], default='other', max_length=20)),
                ('unit', models.CharField(choices=[('bags', 'Bags'), ('kg', 'Kg'), ('ton', 'Ton'), ('pieces', 'Pieces'), ('meter', 'Meter'), ('sqft', 'Sqft'), ('litre', 'Litre'), ('cubic_meter', 'Cubic Meter'), ('nos', 'Nos')], default='pieces', max_length=20)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='suppliers.supplier')),
            ],
            options={
                'db_table': 'materials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('usage', 'Usage'), ('return', 'Return'), ('damage', 'Damage'), ('transfer', 'Transfer'), ('adjustment', 'Adjustment')], max_length=15)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='materials.material')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions', to='projects.project')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier')),
            ],
            options={
                'db_table': 'material_transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
