# Generated by Django 5.1.4 on 2026-09-16 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('weather', models.CharField(choices=[('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('windy', 'Windy'), ('other', 'Other')], default='sunny', max_length=10)),
                ('total_workers', models.PositiveIntegerField(default=0)),
                ('present_workers', models.PositiveIntegerField(default=0)),
                ('work_completed', models.TextField(blank=True)),
                ('work_in_progress', models.TextField(blank=True)),
                ('materials_used', models.TextField(blank=True)),
                ('equipment_used', models.TextField(blank=True)),
                ('issues', models.TextField(blank=True)),
                ('safety_incidents', models.TextField(blank=True)),
                ('supervisor_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='projects.project')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_reports',
                'ordering': ['-report_date'],
                'unique_together': {('project', 'report_date')},
            },
        ),
    ]
